id: 55a2dbd2574f41209aba69d8c38330c6
initial_creation_type: ocr
source_metadata:
  volumes:
    79be21f5c1a0441aad5086665b6442cb:
      base_file: v076.txt
      image_group_id: I1PD95922
      title: ''
      total_pages: 1517
      volume_number: 77
